### ISSUE TITLE
How to demo it 

### ISSUE THREAD

**Issue by huongvu1397** [Plazmaz/MongoDB-HoneyProxy#4]
I really like your topic but I can't practice it, I need a specific guide and its results , <3 thank you

**Comment by Plazmaz** [comment]
Sorry, but I am not entirely sure what you're asking here. What's unclear? What did you try, and where did things fall apart?

**Comment by huongvu1397** [comment]
![image](https://user-images.githubusercontent.com/39198328/56553722-94b8b980-65b9-11e9-92a4-4bb0d82f687e.png)

Thank you for replying, I've finished here, and then I don't know what else to do to use it. So i want some examples to practice it.  😄

**Comment by Plazmaz** [comment]
Oof, looks like I managed to break things a while back without noticing it. I will try to get a fix out.

**Comment by Plazmaz** [comment]
Alright, I think it should work significantly better now if you update to the latest version. Please let me know if you continue to experience issues after pulling down the latest code.

**Comment by huongvu1397** [comment]
Hi, i'm back ,
I tried running it, sometimes it's working but recently it reported a bug like this
![image](https://user-images.githubusercontent.com/39198328/57060777-d09ffd00-6ce4-11e9-9c1d-e2c615d4356f.png)

**Comment by huongvu1397** [comment]
This is how I run it, is it true?
![image](https://user-images.githubusercontent.com/39198328/57061066-caf6e700-6ce5-11e9-9326-3f154fcf20cf.png)

**Comment by Plazmaz** [comment]
Interesting. It looks like a client sent you invalid BSON. Did the program crash or just print an error?
