### ISSUE TITLE
events.js:183  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by pechettibhaskar** [Plazmaz/MongoDB-HoneyProxy#7]
![image](https://user-images.githubusercontent.com/55787564/80605647-f9221a80-8a50-11ea-9024-93792cd83a28.png)
While running "node  index.js" I am getting above error.

OS Version:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS

MongoDB  Version:
MongoDB shell version v4.2.6

nodejs -v
v8.17.0
npm -v
6.13.4

**Comment by Plazmaz** [comment]
Please make sure you don't already have something running on 27017 (like mongo). This project binds to port 27017 by default and the error you provided seems to suggest it's failing to do that.

**Comment by pechettibhaskar** [comment]
@Plazmaz Thanks a lot, it is working perfectly.

**Comment by Plazmaz** [comment]
Happy to hear it.
