### ISSUE TITLE
events.js:183 throw er; // Unhandled 'error' event 

### ISSUE THREAD

**Issue by ajinwu** [Plazmaz/MongoDB-HoneyProxy#8]
hello, I have an same questions with you [this](https://github.com/Plazmaz/MongoDB-HoneyProxy/issues/7), but you not give our methods, can you tell me  how to solve it, thanks very much

**Comment by Plazmaz** [comment]
Change the port you're running mongo on and firewall off public access, then set this Honeypot up on port 27017, and set it to forward to the other port

**Comment by ajinwu** [comment]
but I do not have mongodb server, I only have mongodb clients to test connection, and I will use it my host or docker container, but that not connect too.

let me see

this photo is docker.    https://imgchr.com/i/YLcwUU
that is my real host, it is same error
https://imgchr.com/i/YLcUbV
https://imgchr.com/i/YLcdET

**Comment by ajinwu** [comment]
sorry, thanks for your help, happy wishes

**Comment by Plazmaz** [comment]
No problem! Just in case someone else stumbles across this:
You need to be running a real mongodb server (with dummy data) for this project to work. It's just a logging proxy, not an emulator!
